const imageLookup = {
  React: "/react.svg",
  HTML5: "/html5.svg",
  CSS3: "/css3.svg",
  JavaScript: "/javascript.svg",
  TypeScript: "/typescript.svg",
  Git: "/git.svg",
  Tailwind: "/tailwindcss.svg",
  Node: "/nodejs.svg",
  Express: "/express.svg",
  MongoDB: "/mongodb.svg",
  Figma: "/figma.svg",
  Firebase: "/firebase.svg",
  Illustrator: "/illustrator.svg",
  Linux: "/linux.svg",
  Photoshop: "/photoshop.svg",
  PostgreSQL: "/postgresql.svg",
  Python: "/python.svg",
  Rust: "/rust.svg",
  Vite: "/vite.svg",
  Vercel: "/vercel.svg",
  Supabase: "/supabase.svg",
};

export default imageLookup;